[workspace]
resolver = "3"
members = [
    "common",
    "client",
    "manager"
]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
overlay_common = { version = "0.1", path = './common' }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = { version = "0.1", default-features = false }
dotenvy = "0.15.7"
uuid = { version = "1.17.0", features = ["v4"] }
tokio = {  version = "1.46.1", features = ["full"] }
tokio-tungstenite = "0.21.0"
tungstenite = "0.21.0"

#[workspace.package]
#edition = "2021"
#license = "MIT"
#repository = "https://github.com/jackzmc/game-overlay"