[package]
name = "overlay_ui"
publish = false
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
egui = { version = "0.29", default-features = false }
tracing = { version = "0.1", default-features = false }
egui_overlay = { version = "0.9", features = ["three_d"]}
egui_window_glfw_passthrough = { version = "0.9" }